from datetime import date

import pytest

from dob.state import State
from dob.tasks import (
    Task,
    due_label,
    parse_due,
    render_board,
    render_card,
    render_reminder,
    render_vault_page,
    week_tasks_line,
)

WED = date(2026, 9, 9)  # a Wednesday


@pytest.mark.parametrize(
    ("text", "expected"),
    [
        (None, None),
        ("", None),
        ("none", None),
        ("today", WED),
        ("tomorrow", date(2026, 9, 10)),
        ("fri", date(2026, 9, 11)),
        ("Friday", date(2026, 9, 11)),
        ("wed", date(2026, 9, 16)),  # today's weekday means next week
        ("next fri", date(2026, 9, 18)),
        ("next week", date(2026, 9, 14)),
        ("eow", date(2026, 9, 11)),
        ("in 3 days", date(2026, 9, 12)),
        ("2w", date(2026, 9, 23)),
        ("2026-10-01", date(2026, 10, 1)),
        ("9/12", date(2026, 9, 12)),
        ("9/12/27", date(2027, 9, 12)),
        ("12/1/2026", date(2026, 12, 1)),
    ],
)
def test_parse_due(text, expected):
    assert parse_due(text, WED) == expected


@pytest.mark.parametrize("text", ["someday", "2/30", "13/1", "2026-13-01"])
def test_parse_due_rejects_garbage(text):
    with pytest.raises(ValueError, match="today"):
        parse_due(text, WED)


def test_due_label():
    assert due_label(None, WED) == "no due date"
    assert due_label("2026-09-07", WED) == "overdue by 2d (2026-09-07)"
    assert due_label("2026-09-09", WED) == "due today"
    assert due_label("2026-09-10", WED) == "due tomorrow"
    assert due_label("2026-09-11", WED) == "due Fri (2026-09-11)"
    assert due_label("2026-09-30", WED) == "due 2026-09-30"


def _task(i, title, *, who=None, who_id=None, due=None, status="open", done_at=None):
    return Task(
        id=i,
        title=title,
        notes=None,
        assignee_id=who_id,
        assignee_name=who,
        due=due,
        status=status,
        created_by_id=1,
        created_by="Jordan Blake",
        created_at="2026-09-01T10:00:00+00:00",
        updated_at="2026-09-01T10:00:00+00:00",
        done_at=done_at,
        message_id=None,
        source_url=None,
    )


def test_render_card_open_and_done():
    t = _task(3, "Send Sam the renewal clause", who="Sam", who_id=42, due="2026-09-07")
    card = render_card(t, WED)
    assert card.startswith("🔴 ☐ **#3 · Send Sam the renewal clause**")
    assert "<@42> · overdue by 2d (2026-09-07) · added by Jordan Blake" in card
    assert "/task done id:3" in card
    t.status, t.done_at = "done", "2026-09-08T12:00:00+00:00"
    card = render_card(t, WED)
    assert card.startswith("✅ **~~#3 · Send Sam the renewal clause~~**")
    assert "closed 2026-09-08" in card and "/task done" not in card


def test_render_board_groups_and_orders():
    tasks = [
        _task(1, "No date", who="Sam"),
        _task(2, "Soon", who="Jordan Blake", due="2026-09-12"),
        _task(3, "Late", who="Jordan Blake", due="2026-09-01"),
        _task(4, "Orphan", due="2026-09-09"),
        _task(5, "Done", who="Sam", status="done"),
    ]
    board = render_board(tasks, WED)
    assert board.startswith("**Open tasks** · 2026-09-09 · 4 open")
    assert board.index("**Jordan Blake**") < board.index("**Sam**") < board.index("**Unassigned**")
    assert board.index("🔴 #3 Late") < board.index("#2 Soon")
    assert "🟡 #4 Orphan" in board and "Done" not in board
    assert "Nothing open" in render_board([tasks[4]], WED)


def test_render_reminder_only_when_needed():
    assert render_reminder([_task(1, "Later", due="2026-09-20")], WED) is None
    text = render_reminder(
        [
            _task(1, "Late", who_id=7, due="2026-09-01"),
            _task(2, "Today", who_id=8, due="2026-09-09"),
            _task(3, "Closed late", who_id=7, due="2026-09-01", status="done"),
        ],
        WED,
    )
    assert text is not None
    assert "**Overdue**\n• #1 Late — <@7>" in text
    assert "**Due today**\n• #2 Today — <@8>" in text
    assert "Closed late" not in text


def test_render_vault_page_and_week_line():
    tasks = [
        _task(1, "Open | pipe", who="Sam", due="2026-09-12"),
        _task(2, "Old closed", who="Sam", status="done", done_at="2026-07-01T00:00:00"),
        _task(3, "New closed", status="cancelled", done_at="2026-09-08T00:00:00"),
        _task(4, "Late", who="Jordan Blake", due="2026-09-01"),
    ]
    page = render_vault_page(tasks, WED)
    assert page.startswith("<!-- generated by discord-obsidian-bot")
    assert "| 1 | Open ／ pipe | [[Sam]] | 2026-09-12 | 2026-09-01 |" in page
    assert "| 3 | New closed |  |  | cancelled 2026-09-08 |" in page
    assert "Old closed" not in page
    line = week_tasks_line(tasks, WED)
    assert line.startswith("**Tasks:** 2 open, 1 overdue, 1 due this week")
    assert "• #4 Late — Jordan Blake · overdue by 8d" in line
    assert week_tasks_line([tasks[1]], WED) == ""


def test_state_task_crud(tmp_path):
    st = State(tmp_path / "state.db")
    tid = st.add_task(
        title="Write the pitch",
        notes=None,
        assignee_id=42,
        assignee_name="Sam",
        due="2026-09-12",
        created_by_id=1,
        created_by="Jordan Blake",
        source_url=None,
    )
    assert tid == 1
    t = Task.from_row(st.get_task(tid))
    assert t.title == "Write the pitch" and t.status == "open" and t.assignee_name == "Sam"
    st.update_task(tid, message_id=555, due=None)
    assert Task.from_row(st.task_by_message(555)).due is None
    st.update_task(tid, status="done", done_at="2026-09-10T00:00:00+00:00")
    assert [t.id for t in map(Task.from_row, st.list_tasks(status="open"))] == []
    assert [t.id for t in map(Task.from_row, st.list_tasks())] == [1]
    st.add_task(title="Second", assignee_id=42, assignee_name="Sam", due="2026-09-01")
    st.add_task(title="Third", assignee_id=43, assignee_name="Jordan Blake")
    assert [t.id for t in map(Task.from_row, st.list_tasks(status="open", assignee_id=42))] == [2]
    assert [t.id for t in map(Task.from_row, st.list_tasks(status="open"))] == [2, 3]
    with pytest.raises(ValueError):
        st.update_task(tid, bogus=1)
    assert st.get_task(999) is None
