"""VaultWriter: render notes into the Obsidian vault, maintain entity pages, Home.md, and git.

Rules that keep the vault safe to auto-write:
- Source notes are written once per ingest (overwritten only on force re-ingest).
- Entity/decision pages get exactly two mutations: a bullet appended under `## Mentions`
  (skipped if the same source link is already there) and new aliases unioned into frontmatter.
  Their body text is never rewritten.
- Home.md is fully generated and says so on its first line.
"""

from __future__ import annotations

import logging
import re
import shutil
import subprocess
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path
from zoneinfo import ZoneInfo

import frontmatter
import yaml

from .config import VaultConfig
from .models import DecisionOut, EntityOut, Extracted, Segment, Structured, WrittenNote
from .structure import KnownContext, KnownDecision, KnownEntity

log = logging.getLogger(__name__)

KIND_FOLDER = {
    "recording": "sources/recordings",
    "memo": "sources/memos",
    "document": "sources/documents",
    "chat-digest": "sources/chat-digests",
}
ENTITY_FOLDER = {"person": "people", "project": "projects", "topic": "topics"}
FOLDERS = [*KIND_FOLDER.values(), "chat", *ENTITY_FOLDER.values(), "decisions", "attachments"]
MEDIA_EXT = {
    ".mp3", ".wav", ".m4a", ".ogg", ".oga", ".flac", ".opus", ".aac", ".wma",
    ".mp4", ".mkv", ".mov", ".webm", ".avi",
}  # fmt: skip
HOME_BANNER = "<!-- generated by discord-obsidian-bot; edits to this file will be overwritten -->"
VAULT_GITIGNORE = ".obsidian/workspace*.json\n.obsidian/cache\n.trash/\n"

_BAD_CHARS = re.compile(r'[\\/:*?"<>|\x00-\x1f]')
_WS = re.compile(r"\s+")


def slugify(s: str, max_len: int = 60) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")
    return s[:max_len].rstrip("-") or "untitled"


def safe_name(s: str, max_len: int = 80) -> str:
    s = _WS.sub(" ", _BAD_CHARS.sub("", s)).strip(" .")
    return s[:max_len].strip(" .") or "untitled"


def hms(seconds: float) -> str:
    seconds = int(seconds)
    return f"{seconds // 3600:02d}:{seconds % 3600 // 60:02d}:{seconds % 60:02d}"


def link(target: str, label: str | None = None) -> str:
    return f"[[{target}|{label}]]" if label and label != target else f"[[{target}]]"


def dump_note(meta: dict, body: str) -> str:
    fm = yaml.safe_dump(meta, sort_keys=False, allow_unicode=True, default_flow_style=None).strip()
    return f"---\n{fm}\n---\n{body.rstrip()}\n"


def load_note(path: Path) -> tuple[dict, str]:
    post = frontmatter.load(path, encoding="utf-8")
    return dict(post.metadata), post.content


def render_transcript(segments: list[Segment]) -> str:
    lines = []
    for s in segments:
        who = f" {s.speaker}:" if s.speaker else ""
        lines.append(f"[{hms(s.start)}]{who} {s.text.strip()}")
    return "\n".join(lines)


@dataclass
class _Resolved:
    """An entity mention resolved against the vault."""

    type: str
    name: str
    path: Path
    created: bool


class VaultWriter:
    def __init__(
        self,
        root: Path,
        *,
        cfg: VaultConfig | None = None,
        tz: ZoneInfo | None = None,
        git_commit: bool = False,
        git_push: bool = False,
        remote_url: str = "",
    ):
        self.root = Path(root)
        self.cfg = cfg or VaultConfig()
        self.tz = tz or ZoneInfo("UTC")
        self.git_commit = git_commit
        self.git_push = git_push
        self.remote_url = remote_url
        self._ctx: KnownContext | None = None

    # --- layout -------------------------------------------------------------------

    def ensure_layout(self) -> None:
        self.root.mkdir(parents=True, exist_ok=True)
        for f in FOLDERS:
            (self.root / f).mkdir(parents=True, exist_ok=True)
        gi = self.root / ".gitignore"
        if self.git_commit and not gi.exists():
            gi.write_text(VAULT_GITIGNORE, encoding="utf-8")
        if not (self.root / "Home.md").exists():
            self.regenerate_home()
        if self.git_commit:
            self._ensure_git()

    def rel(self, path: Path) -> str:
        return path.relative_to(self.root).as_posix()

    @staticmethod
    def to_link(rel_path: str) -> str:
        return rel_path.removesuffix(".md")

    # --- known entities --------------------------------------------------------------

    def entity_context(self) -> KnownContext:
        if self._ctx is None:
            self._ctx = self._scan()
        return self._ctx

    def _invalidate(self) -> None:
        self._ctx = None

    def _scan(self) -> KnownContext:
        ctx = KnownContext()
        for etype, folder in ENTITY_FOLDER.items():
            for p in sorted((self.root / folder).glob("*.md")):
                try:
                    meta, _ = load_note(p)
                except Exception:  # noqa: BLE001 - a hand-edited page must not break ingest
                    log.warning("could not parse %s; skipping", p)
                    continue
                if meta.get("type", etype) != etype:
                    continue
                aliases = meta.get("aliases") or []
                if isinstance(aliases, str):
                    aliases = [aliases]
                ctx.entities.append(
                    KnownEntity(
                        type=etype,
                        name=str(meta.get("name") or p.stem),
                        aliases=[str(a) for a in aliases],
                        path=self.rel(p),
                        last_mention=str(meta.get("updated") or meta.get("created") or ""),
                    )
                )
        for p in sorted((self.root / "decisions").glob("*.md")):
            try:
                meta, _ = load_note(p)
            except Exception:  # noqa: BLE001
                continue
            ctx.decisions.append(
                KnownDecision(title=str(meta.get("title") or p.stem), path=self.rel(p))
            )
        ctx.entities.sort(key=lambda e: e.last_mention, reverse=True)
        return ctx

    def _find_entity(self, etype: str, name: str, aliases: list[str] = ()) -> KnownEntity | None:
        """Resolve a mention. The canonical name may match a known name or alias; the mention's
        own aliases only match known *names*, so a new person nicknamed "Jordan" never hijacks an
        existing "Jordan Blake" whose alias is "Jordan"."""
        key = name.casefold()
        known = [k for k in self.entity_context().entities if k.type == etype]
        for k in known:
            if k.name.casefold() == key or any(a.casefold() == key for a in k.aliases):
                return k
        alias_keys = {a.casefold() for a in aliases if a}
        for k in known:
            if k.name.casefold() in alias_keys:
                return k
        return None

    def _find_decision(self, title: str) -> KnownDecision | None:
        key = title.casefold().strip()
        for d in self.entity_context().decisions:
            if d.title.casefold().strip() == key:
                return d
        return None

    # --- main entry ------------------------------------------------------------------

    def write(self, extracted: Extracted, structured: Structured) -> WrittenNote:
        self.ensure_layout()
        out = structured.output
        item = extracted.item
        when = self._item_date(extracted)
        title = safe_name(out.suggested_title or item.original_name, 60)
        note_path = self._note_path(extracted, title, when)
        note_link = self.to_link(self.rel(note_path))
        result = WrittenNote(note_path=self.rel(note_path), link=note_link, title=title)

        # 1. entities
        resolved: dict[tuple[str, str], _Resolved] = {}
        for ent in out.entities:
            r = self._upsert_entity(ent, when)
            resolved[(ent.type, ent.name.casefold())] = r
            for a in ent.aliases:
                resolved.setdefault((ent.type, a.casefold()), r)
            (result.entities_created if r.created else result.entities_updated).append(r.name)

        def person_link(name: str | None) -> str:
            if not name:
                return ""
            r = resolved.get(("person", name.casefold())) or self._lookup_any(name)
            return link(r.name) if r else name

        # 2. decisions
        decision_links: list[tuple[str, str]] = []
        for d in out.decisions:
            dpath, created = self._upsert_decision(d, when, note_link, title, person_link)
            decision_links.append((self.to_link(self.rel(dpath)), d.title))
            if created:
                result.decisions_created.append(d.title)

        # 3. source note
        original_rel = self._keep_original(extracted)
        meta = self._source_meta(extracted, structured, title, when, person_link, original_rel)
        body = self._source_body(
            extracted, structured, title, resolved, decision_links, person_link
        )
        note_path.write_text(dump_note(meta, body), encoding="utf-8")

        # 4. mentions on entities and decisions
        for ent in out.entities:
            r = resolved[(ent.type, ent.name.casefold())]
            self._append_mention(r.path, when, note_link, title, ent.role_in_source)
        for (dlink, _dtitle), d in zip(decision_links, out.decisions, strict=True):
            verb = "Reaffirmed" if d.matches_existing else "Decided"
            self._append_mention(self.root / f"{dlink}.md", when, note_link, title, f"{verb} here")

        self._invalidate()
        self.regenerate_home()
        result.commit_sha = self.commit(f"ingest: {title}")
        return result

    # --- chat logs (used by chat.py) -----------------------------------------------------

    def write_chat_log(self, channel_name: str, day: str, meta: dict, body: str) -> str:
        self.ensure_layout()
        folder = self.root / "chat" / safe_name(channel_name)
        folder.mkdir(parents=True, exist_ok=True)
        p = folder / f"{day}.md"
        p.write_text(dump_note(meta, body), encoding="utf-8")
        return self.rel(p)

    def chat_digest_link(self, channel_name: str, day: str) -> str:
        return f"{KIND_FOLDER['chat-digest']}/{safe_name(channel_name)}/{day}"

    # --- pieces ------------------------------------------------------------------------

    def _item_date(self, extracted: Extracted) -> date:
        item = extracted.item
        if item.day:
            return date.fromisoformat(item.day)
        if item.discord:
            return item.discord.created_at.astimezone(self.tz).date()
        return datetime.now(self.tz).date()

    def _note_path(self, extracted: Extracted, title: str, when: date) -> Path:
        item = extracted.item
        if extracted.kind == "chat-digest":
            folder = (
                self.root / KIND_FOLDER["chat-digest"] / safe_name(item.channel_name or "channel")
            )
            folder.mkdir(parents=True, exist_ok=True)
            return folder / f"{when.isoformat()}.md"
        folder = self.root / KIND_FOLDER[extracted.kind]
        base = f"{when.isoformat()} {slugify(title)}"
        p = folder / f"{base}.md"
        if p.exists() and not item.force and self._sha_of(p) != item.sha256:
            p = folder / f"{base}-{(item.sha256 or item.id)[:8]}.md"
        return p

    @staticmethod
    def _sha_of(p: Path) -> str | None:
        try:
            meta, _ = load_note(p)
            return meta.get("sha256")
        except Exception:  # noqa: BLE001
            return None

    def _lookup_any(self, name: str) -> _Resolved | None:
        for etype in ENTITY_FOLDER:
            k = self._find_entity(etype, name)
            if k:
                return _Resolved(type=etype, name=k.name, path=self.root / k.path, created=False)
        return None

    def _upsert_entity(self, ent: EntityOut, when: date) -> _Resolved:
        names = [ent.name, *ent.aliases]
        known = self._find_entity(ent.type, ent.name, ent.aliases)
        if known:
            path = self.root / known.path
            self._union_aliases(
                path, known, [n for n in names if n.casefold() != known.name.casefold()]
            )
            return _Resolved(type=ent.type, name=known.name, path=path, created=False)
        name = safe_name(ent.name)
        folder = self.root / ENTITY_FOLDER[ent.type]
        path = folder / f"{name}.md"
        if path.exists():  # exists on disk but was not in the context (e.g. type mismatch)
            return _Resolved(type=ent.type, name=name, path=path, created=False)
        aliases = self._clean_aliases(ent.type, name, ent.aliases)
        meta = {
            "type": ent.type,
            "name": name,
            "aliases": aliases,
            "created": when.isoformat(),
            "updated": when.isoformat(),
            "tags": [],
        }
        desc = (ent.description or "").strip()
        body = f"# {name}\n\n{desc}\n\n## Mentions\n" if desc else f"# {name}\n\n## Mentions\n"
        path.write_text(dump_note(meta, body), encoding="utf-8")
        self._invalidate()
        return _Resolved(type=ent.type, name=name, path=path, created=True)

    def _clean_aliases(self, etype: str, name: str, aliases: list[str]) -> list[str]:
        """Drop aliases that are (or alias) another entity, so "Jordan" never points two ways."""
        taken: set[str] = set()
        for e in self.entity_context().entities:
            if e.name.casefold() == name.casefold() and e.type == etype:
                continue
            taken.add(e.name.casefold())
            taken.update(a.casefold() for a in e.aliases)
        out: list[str] = []
        for a in aliases:
            a = _WS.sub(" ", a).strip()
            if not a or a.casefold() == name.casefold() or a.casefold() in taken:
                continue
            if a.casefold() not in {o.casefold() for o in out}:
                out.append(a)
        return out

    def _union_aliases(self, path: Path, known: KnownEntity, new: list[str]) -> None:
        add = [
            a
            for a in self._clean_aliases(known.type, known.name, new)
            if a.casefold() not in {k.casefold() for k in known.aliases}
        ]
        if not add:
            return
        meta, body = load_note(path)
        aliases = list(meta.get("aliases") or [])
        aliases.extend(add)
        meta["aliases"] = aliases
        path.write_text(dump_note(meta, body), encoding="utf-8")
        known.aliases.extend(add)

    def _upsert_decision(
        self, d: DecisionOut, when: date, note_link: str, note_title: str, person_link
    ) -> tuple[Path, bool]:
        existing = None
        if d.matches_existing:
            existing = self._find_decision(d.matches_existing)
        if existing is None:
            existing = self._find_decision(d.title)
        if existing:
            return self.root / existing.path, False
        title = safe_name(d.title, 80)
        path = self.root / "decisions" / f"{when.isoformat()} {slugify(title)}.md"
        if path.exists():
            path = path.with_name(f"{path.stem}-{len(self.entity_context().decisions) + 1}.md")
        meta = {
            "type": "decision",
            "title": title,
            "decided_on": when.isoformat(),
            "status": "decided",
            "decided_by": [person_link(p) for p in d.decided_by],
            "source": link(note_link, note_title),
            "tags": [],
        }
        body = f"# {title}\n\n## Statement\n{d.statement.strip()}\n"
        if d.rationale:
            body += f"\n## Rationale\n{d.rationale.strip()}\n"
        body += "\n## Mentions\n"
        path.write_text(dump_note(meta, body), encoding="utf-8")
        self._invalidate()
        return path, True

    def _append_mention(
        self, path: Path, when: date, note_link: str, note_title: str, role: str
    ) -> None:
        if not path.exists():
            return
        meta, body = load_note(path)
        if f"[[{note_link}" in body:
            return
        bullet = f"- {when.isoformat()} — {link(note_link, note_title)} — {role.strip()}".rstrip(
            " —"
        )
        if "## Mentions" not in body:
            body = body.rstrip() + "\n\n## Mentions\n"
        body = body.rstrip("\n") + "\n" + bullet + "\n"
        if "updated" in meta or meta.get("type") in ENTITY_FOLDER:
            meta["updated"] = when.isoformat()
        path.write_text(dump_note(meta, body), encoding="utf-8")

    def _keep_original(self, extracted: Extracted) -> str | None:
        item = extracted.item
        p = item.local_path
        if not p or not Path(p).exists() or extracted.kind not in ("document",):
            return None
        p = Path(p)
        if p.suffix.lower() in MEDIA_EXT:
            return None
        if p.stat().st_size > self.cfg.keep_originals_max_mb * 1024 * 1024:
            return None
        dest = self.root / "attachments" / f"{(item.sha256 or item.id)[:8]}-{safe_name(p.name)}"
        if not dest.exists():
            shutil.copy2(p, dest)
        return self.rel(dest)

    def _source_meta(self, extracted, structured, title, when, person_link, original_rel) -> dict:
        item = extracted.item
        out = structured.output
        meta: dict = {
            "type": extracted.kind,
            "title": title,
            "source": item.source,
            "source_ref": item.source_ref,
        }
        if item.discord:
            meta["discord_link"] = item.discord.jump_url
            meta["channel"] = f"#{item.discord.channel_name}"
            meta["posted_by"] = person_link(item.discord.author_name)
        elif item.channel_name:
            meta["channel"] = f"#{item.channel_name}"
        if item.url:
            meta["url"] = item.url
        meta["date"] = when.isoformat()
        meta["ingested_at"] = datetime.now(self.tz).isoformat(timespec="seconds")
        if out.participants:
            meta["participants"] = [person_link(p) for p in out.participants]
        if extracted.duration_s:
            meta["duration"] = hms(extracted.duration_s)
        if extracted.language:
            meta["language"] = extracted.language
        if extracted.page_count:
            meta["pages"] = extracted.page_count
        if extracted.kind == "chat-digest":
            meta["message_count"] = int(extracted.meta.get("message_count", 0) or 0)
            if item.channel_name and item.day:
                meta["log"] = link(f"chat/{safe_name(item.channel_name)}/{item.day}")
        if original_rel:
            meta["original"] = link(
                self.to_link(original_rel) if original_rel.endswith(".md") else original_rel
            )
        for k, v in extracted.meta.items():
            if k not in meta and k not in ("message_count",):
                meta[k] = v
        if item.sha256:
            meta["sha256"] = item.sha256
        meta["tags"] = [slugify(t, 40) for t in out.tags]
        meta["model"] = structured.model
        return meta

    def _source_body(
        self, extracted, structured, title, resolved, decision_links, person_link
    ) -> str:
        out = structured.output
        parts = [f"# {title}", "", "## Summary", out.summary.strip(), ""]
        if out.key_points:
            parts += ["## Key points", *[f"- {k.strip()}" for k in out.key_points], ""]
        if decision_links:
            parts += ["## Decisions", *[f"- {link(dl, dt)}" for dl, dt in decision_links], ""]
        if out.action_items:
            parts.append("## Action items")
            for a in out.action_items:
                s = f"- [ ] {a.task.strip()}"
                if a.owner:
                    s += f" — {person_link(a.owner)}"
                if a.due:
                    s += f" (due {a.due})"
                parts.append(s)
            parts.append("")
        if out.entities:
            parts.append("## Entities")
            for etype, label in (
                ("person", "People"),
                ("project", "Projects"),
                ("topic", "Topics"),
            ):
                names = []
                for e in out.entities:
                    if e.type == etype:
                        r = resolved[(e.type, e.name.casefold())]
                        if link(r.name) not in names:
                            names.append(link(r.name))
                if names:
                    parts.append(f"- {label}: {', '.join(names)}")
            parts.append("")
        if extracted.kind == "chat-digest":
            threads = extracted.meta.get("threads", "")
            if threads:
                parts += ["## Threads", *[f"- {t}" for t in threads.split("\n") if t], ""]
        elif extracted.segments:
            parts += ["## Transcript", render_transcript(extracted.segments), ""]
        else:
            parts += ["## Extracted text", extracted.text.strip(), ""]
        return "\n".join(parts)

    # --- Home.md ----------------------------------------------------------------------

    def regenerate_home(self) -> None:
        sources = []
        for kind, folder in KIND_FOLDER.items():
            for p in (self.root / folder).rglob("*.md"):
                try:
                    meta, body = load_note(p)
                except Exception:  # noqa: BLE001
                    continue
                m = re.search(r"## Summary\n+(.+)", body)
                sources.append(
                    {
                        "kind": kind,
                        "title": str(meta.get("title") or p.stem),
                        "date": str(meta.get("date") or ""),
                        "ingested_at": str(meta.get("ingested_at") or ""),
                        "link": self.to_link(self.rel(p)),
                        "summary": (m.group(1).strip() if m else "")[:160],
                        "body": body,
                    }
                )
        sources.sort(key=lambda s: s["ingested_at"], reverse=True)
        decisions = []
        for p in (self.root / "decisions").glob("*.md"):
            try:
                meta, _ = load_note(p)
            except Exception:  # noqa: BLE001
                continue
            decisions.append(
                (
                    str(meta.get("decided_on") or ""),
                    str(meta.get("title") or p.stem),
                    self.to_link(self.rel(p)),
                )
            )
        decisions.sort(reverse=True)
        counts = {
            "sources": len(sources),
            "people": len(list((self.root / "people").glob("*.md"))),
            "projects": len(list((self.root / "projects").glob("*.md"))),
            "topics": len(list((self.root / "topics").glob("*.md"))),
            "decisions": len(decisions),
            "chat days": len(list((self.root / "chat").rglob("*.md"))),
        }
        lines = [
            HOME_BANNER,
            "",
            "# Home",
            "",
            "| " + " | ".join(counts) + " |",
            "|" + "---|" * len(counts),
            "| " + " | ".join(str(v) for v in counts.values()) + " |",
            "",
        ]
        lines += ["## Recent sources", ""]
        for s in sources[:30]:
            lines.append(
                f"- {s['date']} · {s['kind']} · {link(s['link'], s['title'])} — {s['summary']}".rstrip(
                    " —"
                )
            )
        lines += ["", "## Recent decisions", ""]
        for d_on, d_title, d_link in decisions[:15]:
            lines.append(f"- {d_on} · {link(d_link, d_title)}")
        lines += ["", "## Open action items (last 30 days)", ""]
        cutoff = datetime.now(self.tz).date().toordinal() - 30
        for s in sources:
            try:
                if date.fromisoformat(s["date"]).toordinal() < cutoff:
                    continue
            except ValueError:
                continue
            for ln in s["body"].splitlines():
                if ln.startswith("- [ ] "):
                    lines.append(f"{ln}  ({link(s['link'], s['title'])})")
        lines += [
            "",
            "## Browse",
            "",
            "- [[people/]] · [[projects/]] · [[topics/]] · [[decisions/]] · [[chat/]]",
            "",
        ]
        (self.root / "Home.md").write_text("\n".join(lines), encoding="utf-8")

    # --- git ------------------------------------------------------------------------------

    def _git(self, *args: str, check: bool = False) -> subprocess.CompletedProcess:
        return subprocess.run(
            ["git", *args], cwd=self.root, capture_output=True, text=True, check=check
        )

    def _ensure_git(self) -> None:
        if (self.root / ".git").exists():
            return
        self._git("init", "-q", "-b", "main", check=True)
        log.info("initialised git repo in %s", self.root)

    def commit(self, message: str) -> str | None:
        if not self.git_commit:
            return None
        self._ensure_git()
        self._git("add", "-A")
        if self._git("diff", "--cached", "--quiet").returncode == 0:
            return None
        ident: list[str] = []
        if not self._git("config", "user.name").stdout.strip():
            ident = ["-c", "user.name=discord-obsidian-bot", "-c", "user.email=bot@localhost"]
        r = self._git(*ident, "commit", "-q", "-m", message)
        if r.returncode != 0:
            log.warning("git commit failed: %s", r.stderr.strip())
            return None
        sha = self._git("rev-parse", "--short", "HEAD").stdout.strip()
        if self.git_push:
            self._push()
        return sha or None

    def _push(self) -> None:
        if self.remote_url:
            if self._git("remote", "get-url", "origin").returncode != 0:
                self._git("remote", "add", "origin", self.remote_url)
            else:
                self._git("remote", "set-url", "origin", self.remote_url)
        r = self._git("push", "-q", "-u", "origin", "HEAD")
        if r.returncode != 0:
            log.warning("git push failed: %s", r.stderr.strip()[-500:])
